2024-01-10 10:05:22.232 WARNING (Recorder) [homeassistant.components.recorder.util] The system could not validate that the sqlite3 database at //config/home-assistant_v2.db was shutdown cleanly
2024-01-10 10:05:31.722 ERROR (MainThread) [homeassistant.components.homeassistant_alerts] Error requesting homeassistant_alerts data: Cannot connect to host alerts.home-assistant.io:443 ssl:default [Try again]
2024-01-10 10:31:55.842 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=27 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=27, family=2, type=2, proto=0, laddr=('0.0.0.0', 58579)>
2024-01-10 10:31:55.842 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=30 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=30, family=10, type=2, proto=0, laddr=('::', 50816, 0, 0)>
2024-01-10 10:34:25.847 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=27 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=27, family=2, type=2, proto=0, laddr=('0.0.0.0', 58579)>
2024-01-10 10:34:25.847 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=30 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=30, family=10, type=2, proto=0, laddr=('::', 50816, 0, 0)>
2024-01-10 10:34:55.849 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=27 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=27, family=2, type=2, proto=0, laddr=('0.0.0.0', 58579)>
2024-01-10 10:34:55.849 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=30 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=30, family=10, type=2, proto=0, laddr=('::', 50816, 0, 0)>
2024-01-10 10:35:21.587 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=20 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=20, family=2, type=2, proto=0, laddr=('0.0.0.0', 40521)>
2024-01-10 10:35:21.588 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=21 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=21, family=10, type=2, proto=0, laddr=('::', 36932, 0, 0)>
2024-01-10 10:35:21.588 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=20 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=20, family=2, type=2, proto=0, laddr=('0.0.0.0', 40521)>
2024-01-10 10:35:25.850 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=27 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=27, family=2, type=2, proto=0, laddr=('0.0.0.0', 58579)>
2024-01-10 10:35:25.850 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=30 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=30, family=10, type=2, proto=0, laddr=('::', 50816, 0, 0)>
2024-01-10 10:40:25.863 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=27 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=27, family=2, type=2, proto=0, laddr=('0.0.0.0', 58579)>
2024-01-10 10:40:25.864 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=30 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=30, family=10, type=2, proto=0, laddr=('::', 50816, 0, 0)>
2024-01-10 10:40:55.864 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=27 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=27, family=2, type=2, proto=0, laddr=('0.0.0.0', 58579)>
2024-01-10 10:40:55.865 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=30 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=30, family=10, type=2, proto=0, laddr=('::', 50816, 0, 0)>
2024-01-10 10:41:25.865 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=27 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=27, family=2, type=2, proto=0, laddr=('0.0.0.0', 58579)>
2024-01-10 10:41:25.866 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=30 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=30, family=10, type=2, proto=0, laddr=('::', 50816, 0, 0)>
2024-01-10 10:41:55.867 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=27 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=27, family=2, type=2, proto=0, laddr=('0.0.0.0', 58579)>
2024-01-10 10:41:55.867 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=30 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=30, family=10, type=2, proto=0, laddr=('::', 50816, 0, 0)>
2024-01-10 10:42:25.868 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=27 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=27, family=2, type=2, proto=0, laddr=('0.0.0.0', 58579)>
2024-01-10 10:42:25.869 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=30 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=30, family=10, type=2, proto=0, laddr=('::', 50816, 0, 0)>
